# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sentiment_pb2 as sentiment__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sentiment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentimentServiceStub(object):
    """SentimentService defines the gRPC service for stock sentiment analysis.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStockSentiment = channel.unary_unary(
                '/sentiment.SentimentService/GetStockSentiment',
                request_serializer=sentiment__pb2.StockSentimentRequest.SerializeToString,
                response_deserializer=sentiment__pb2.SentimentResponse.FromString,
                _registered_method=True)
        self.StreamStockSentiment = channel.unary_stream(
                '/sentiment.SentimentService/StreamStockSentiment',
                request_serializer=sentiment__pb2.StockSentimentStreamRequest.SerializeToString,
                response_deserializer=sentiment__pb2.SentimentResponse.FromString,
                _registered_method=True)


class SentimentServiceServicer(object):
    """SentimentService defines the gRPC service for stock sentiment analysis.
    """

    def GetStockSentiment(self, request, context):
        """GetStockSentiment returns the current sentiment for a stock.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStockSentiment(self, request, context):
        """StreamStockSentiment streams historical sentiment data for a stock.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentimentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStockSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockSentiment,
                    request_deserializer=sentiment__pb2.StockSentimentRequest.FromString,
                    response_serializer=sentiment__pb2.SentimentResponse.SerializeToString,
            ),
            'StreamStockSentiment': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStockSentiment,
                    request_deserializer=sentiment__pb2.StockSentimentStreamRequest.FromString,
                    response_serializer=sentiment__pb2.SentimentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentiment.SentimentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentiment.SentimentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SentimentService(object):
    """SentimentService defines the gRPC service for stock sentiment analysis.
    """

    @staticmethod
    def GetStockSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentiment.SentimentService/GetStockSentiment',
            sentiment__pb2.StockSentimentRequest.SerializeToString,
            sentiment__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStockSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sentiment.SentimentService/StreamStockSentiment',
            sentiment__pb2.StockSentimentStreamRequest.SerializeToString,
            sentiment__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
