# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\tsentiment\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n\x15StockSentimentRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\'\n\ttimeframe\x18\x02 \x01(\x0e\x32\x14.sentiment.Timeframe\"\xb2\x01\n\x1bStockSentimentStreamRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x08interval\x18\x04 \x01(\x0e\x32\x13.sentiment.Interval\"x\n\x11SentimentResponse\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x17\n\x0fsentiment_score\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x18\n\x10\x64\x61ta_point_count\x18\x04 \x01(\x05\x12\r\n\x05\x65rror\x18\x05 \x01(\t*\\\n\tTimeframe\x12\x19\n\x15TIMEFRAME_UNSPECIFIED\x10\x00\x12\x10\n\x0cTIMEFRAME_1H\x10\x01\x12\x10\n\x0cTIMEFRAME_1D\x10\x02\x12\x10\n\x0cTIMEFRAME_1W\x10\x03*W\n\x08Interval\x12\x18\n\x14INTERVAL_UNSPECIFIED\x10\x00\x12\x0f\n\x0bINTERVAL_1M\x10\x01\x12\x0f\n\x0bINTERVAL_1H\x10\x02\x12\x0f\n\x0bINTERVAL_1D\x10\x03\x32\xcb\x01\n\x10SentimentService\x12U\n\x11GetStockSentiment\x12 .sentiment.StockSentimentRequest\x1a\x1c.sentiment.SentimentResponse\"\x00\x12`\n\x14StreamStockSentiment\x12&.sentiment.StockSentimentStreamRequest\x1a\x1c.sentiment.SentimentResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEFRAME']._serialized_start=448
  _globals['_TIMEFRAME']._serialized_end=540
  _globals['_INTERVAL']._serialized_start=542
  _globals['_INTERVAL']._serialized_end=629
  _globals['_STOCKSENTIMENTREQUEST']._serialized_start=63
  _globals['_STOCKSENTIMENTREQUEST']._serialized_end=143
  _globals['_STOCKSENTIMENTSTREAMREQUEST']._serialized_start=146
  _globals['_STOCKSENTIMENTSTREAMREQUEST']._serialized_end=324
  _globals['_SENTIMENTRESPONSE']._serialized_start=326
  _globals['_SENTIMENTRESPONSE']._serialized_end=446
  _globals['_SENTIMENTSERVICE']._serialized_start=632
  _globals['_SENTIMENTSERVICE']._serialized_end=835
# @@protoc_insertion_point(module_scope)
