# api.yaml
# Kubernetes deployment and service definitions for the SentimentService gRPC API.
# Deploys the API container and exposes it via a ClusterIP service for internal access.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-api
  namespace: stock-sentiment
  labels:
    app: sentiment-api
spec:
  replicas: 3  # Run 3 replicas for high availability
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
      annotations:
        # Enable Istio sidecar injection
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: sentiment-api
        image: gcr.io/stock-sentiment-analyzer/stock-sentiment-api:latest  # Replace with your GCP project
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051  # gRPC port
          protocol: TCP
        env:
        - name: GCP_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: sentiment-config
              key: gcp_project_id
        - name: BQ_DATASET
          valueFrom:
            configMapKeyRef:
              name: sentiment-config
              key: bq_dataset
        - name: GRPC_PORT
          value: "50051"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"  # 0.2 CPU
          limits:
            memory: "512Mi"
            cpu: "500m"  # 0.5 CPU
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-api-service
  namespace: stock-sentiment
  labels:
    app: sentiment-api
spec:
  selector:
    app: sentiment-api
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  type: ClusterIP  # Internal service for gRPC communication