steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fresh-rain-454919-b2/stock-sentiment:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fresh-rain-454919-b2/stock-sentiment:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment/k8s/deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sentiment-cluster' 
images:
- 'gcr.io/fresh-rain-454919-b2/stock-sentiment:latest'